Repository lionize/WebUI, pull requests merged in 2019-09, with the labels that each got.

#65 menu component enhancement (direction feature)
  ui/src/app/pages/admin/admin.component.html
  ui/src/app/shared/components/header/header.component.html
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/components/menu/menu.animations.ts
  ui/src/app/shared/components/menu/menu.component.html
  ui/src/app/shared/components/menu/menu.component.scss
  ui/src/app/shared/components/menu/menu.component.ts
  ui/src/app/shared/components/menu/menu.model.ts
  ui/src/app/store/actions/menu.actions.ts
  ui/src/app/store/reducers/app.reducers.ts
  ui/src/app/store/selectors/menu.selectors.ts
  ui/src/app/store/state/app.state.ts
  ui/src/app/store/state/menu.state.ts
  ui/src/styles.scss
Labels: enhancement

#66 refactoring
  ui/src/app/pages/admin/dashboard/dashboard.component.scss
  ui/src/app/shared/components/header/header.component.scss
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/components/li-auth/li-auth.component.ts
  ui/src/app/shared/components/menu/menu.animations.ts
  ui/src/app/shared/components/menu/menu.component.scss
  ui/src/app/shared/guards/auth.guard.ts
  ui/src/app/shared/services/api.service.ts
  ui/src/app/shared/services/message.service.ts
  ui/src/assets/styles/variables.scss
Labels: enhancement

#67 add logo
  ui/src/app/shared/components/header/header.component.html
  ui/src/app/shared/components/header/header.component.scss
  ui/src/assets/images/lionize_logo_large.png
Labels: enhancement

#69 profile page init
  ui/src/app/pages/admin/admin.module.ts
  ui/src/app/pages/admin/admin.routing.module.ts
  ui/src/app/pages/admin/profile/profile.component.html
  ui/src/app/pages/admin/profile/profile.component.scss
  ui/src/app/pages/admin/profile/profile.component.ts
  ui/src/app/shared/components/header/header.component.html
  ui/src/app/shared/shared.module.ts
  ui/src/styles.scss
Labels: enhancement

#70 profile (providers) page
  ui/src/app/pages/admin/admin.module.ts
  ui/src/app/pages/admin/admin.routing.module.ts
  ui/src/app/pages/admin/dashboard/dashboard.component.scss
  ui/src/app/pages/admin/profile/profile.component.html
  ui/src/app/pages/admin/profile/profile.component.scss
  ui/src/app/pages/admin/profile/profile.component.ts
  ui/src/app/pages/admin/providers/providers.component.html
  ui/src/app/pages/admin/providers/providers.component.scss
  ui/src/app/pages/admin/providers/providers.component.ts
  ui/src/app/shared/components/header/header.component.html
  ui/src/app/shared/components/header/header.component.scss
  ui/src/app/shared/components/menu/menu.component.html
  ui/src/app/shared/components/menu/menu.component.scss
  ui/src/assets/styles/reset.css
  ui/src/styles.scss
Labels: enhancement

#71 fixes
  ui/src/app/app.component.ts
  ui/src/app/app.module.ts
  ui/src/app/pages/authentication/user.model.ts
  ui/src/app/shared/components/footer/footer.component.html
  ui/src/app/shared/components/footer/footer.component.scss
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/components/menu/menu.animations.ts
  ui/src/app/shared/components/menu/menu.component.scss
  ui/src/app/shared/components/menu/menu.model.ts
  ui/src/app/store/actions/app.actions.ts
  ui/src/app/store/actions/menu.actions.ts
  ui/src/app/store/reducers/app.reducers.ts
  ui/src/app/store/selectors/app.selectors.ts
  ui/src/assets/styles/common.scss
Labels: enhancement

#72 Feature/add models
  .gitignore
  psakefile.ps1
  ui/apis/habitica/ApiModels.yml
  ui/apis/identity/ApiModels.yml
  ui/apis/tasks/ApiModels.yml
Labels: enhancement

#73 enhancements
  ui/src/app/app.component.ts
  ui/src/app/app.module.ts
  ui/src/app/pages/admin/admin.component.html
  ui/src/app/pages/authentication/authentication.service.ts
  ui/src/app/pages/authentication/user.model.ts
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/components/li-auth/li-auth.component.ts
  ui/src/app/shared/components/menu/menu.component.ts
  ui/src/app/shared/components/menu/menu.model.ts
  ui/src/app/shared/guards/auth.guard.ts
  ui/src/app/store/actions/menu.actions.ts
  ui/src/app/store/reducers/app.reducers.ts
  ui/src/app/store/state/menu.state.ts
  ui/src/assets/styles/variables.scss
Labels: enhancement

#74 theming, styling
  ui/src/app/pages/admin/admin.component.html
  ui/src/app/pages/admin/admin.component.scss
  ui/src/app/shared/components/footer/footer.component.html
  ui/src/app/shared/components/footer/footer.component.scss
  ui/src/app/shared/components/header/header.component.html
  ui/src/app/shared/components/header/header.component.scss
  ui/src/app/shared/components/li-auth/li-auth.component.scss
  ui/src/app/shared/components/menu/menu.component.scss
  ui/src/assets/styles/mixins/admin-theme.component.scss
  ui/src/assets/styles/mixins/app-theme.component.scss
  ui/src/assets/styles/mixins/footer-theme.component.scss
  ui/src/assets/styles/mixins/header-theme.component.scss
  ui/src/assets/styles/mixins/li-auth-theme.component.scss
  ui/src/assets/styles/mixins/menu-theme.component.scss
  ui/src/assets/styles/variables.scss
  ui/src/styles.scss
Labels: enhancement

#75 Providers popup component init
  ui/src/app/app.component.ts
  ui/src/app/pages/admin/admin.module.ts
  ui/src/app/pages/admin/providers/providers.component.html
  ui/src/app/pages/admin/providers/providers.component.ts
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/components/popup/popup.component.html
  ui/src/app/shared/components/popup/popup.component.scss
  ui/src/app/shared/components/popup/popup.component.ts
  ui/src/app/shared/services/api.service.ts
  ui/src/environments/environment.prod.ts
  ui/src/environments/environment.ts
  ui/src/styles.scss
Labels: enhancement

#77 dynamic popup component
  ui/src/app/app.module.ts
  ui/src/app/pages/admin/admin.component.scss
  ui/src/app/pages/admin/admin.module.ts
  ui/src/app/pages/admin/dashboard/dashboard.component.scss
  ui/src/app/pages/admin/providers/providers.component.html
  ui/src/app/pages/admin/providers/providers.component.scss
  ui/src/app/pages/admin/providers/providers.component.ts
  ui/src/app/shared/components/dialog/dialog.component.html
  ui/src/app/shared/components/dialog/dialog.component.scss
  ui/src/app/shared/components/dynamic-components/google/google.component.html
  ui/src/app/shared/components/dynamic-components/google/google.component.scss
  ui/src/app/shared/components/dynamic-components/google/google.component.ts
  ui/src/app/shared/components/dynamic-components/habitica/habitica.component.html
  ui/src/app/shared/components/dynamic-components/habitica/habitica.component.scss
  ui/src/app/shared/components/dynamic-components/habitica/habitica.component.ts
  ui/src/app/shared/components/dynamic-components/microsoft/microsoft.component.html
  ui/src/app/shared/components/dynamic-components/microsoft/microsoft.component.scss
  ui/src/app/shared/components/dynamic-components/microsoft/microsoft.component.ts
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/components/menu/menu.component.scss
  ui/src/app/shared/components/menu/menu.component.ts
  ui/src/app/shared/components/popup/popup.component.html
  ui/src/app/shared/components/popup/popup.component.ts
  ui/src/assets/styles/common.scss
  ui/src/assets/styles/reset.css
  ui/src/styles.scss
Labels: enhancement

#78 habitica component iteraction with popup
  ui/src/app/pages/admin/admin.module.ts
  ui/src/app/pages/admin/providers/providers.component.ts
  ui/src/app/pages/admin/providers/providers.service.ts
  ui/src/app/shared/components/dynamic-components/habitica/habitica.component.html
  ui/src/app/shared/components/dynamic-components/habitica/habitica.component.ts
  ui/src/app/shared/components/dynamic-components/providers/google/google.component.html
  ui/src/app/shared/components/dynamic-components/providers/google/google.component.scss
  ui/src/app/shared/components/dynamic-components/providers/google/google.component.ts
  ui/src/app/shared/components/dynamic-components/providers/habitica/habitica.component.html
  ui/src/app/shared/components/dynamic-components/providers/habitica/habitica.component.scss
  ui/src/app/shared/components/dynamic-components/providers/habitica/habitica.component.ts
  ui/src/app/shared/components/dynamic-components/providers/microsoft/microsoft.component.html
  ui/src/app/shared/components/dynamic-components/providers/microsoft/microsoft.component.scss
  ui/src/app/shared/components/dynamic-components/providers/microsoft/microsoft.component.ts
  ui/src/app/shared/components/popup/popup.component.ts
  ui/src/app/shared/validation.messages.ts
Labels: enhancement

#79 fix: build issue
  ui/src/app/shared/components/dynamic-components/providers/habitica/habitica.component.html
Labels: bug

#80 habitica GET and POST
  ui/src/app/pages/admin/providers/providers.component.html
  ui/src/app/pages/admin/providers/providers.component.ts
  ui/src/app/pages/admin/providers/providers.service.ts
  ui/src/app/pages/authentication/authentication.module.ts
  ui/src/app/pages/authentication/authentication.service.ts
  ui/src/app/shared/components/popup/popup.component.html
  ui/src/app/shared/components/popup/popup.component.ts
  ui/src/app/shared/constants.ts
  ui/src/app/shared/guards/auth.guard.ts
  ui/src/app/shared/helpers/error.interceptor.ts
  ui/src/app/shared/helpers/jwt.interceptors.ts
  ui/src/app/shared/services/api.service.ts
Labels: enhancement

#81 habitica component, other fixes
  ui/src/app/pages/admin/admin.module.ts
  ui/src/app/pages/admin/dashboard/dashboard.component.scss
  ui/src/app/pages/admin/providers/providers.component.html
  ui/src/app/pages/admin/providers/providers.component.scss
  ui/src/app/pages/admin/providers/providers.component.ts
  ui/src/app/pages/admin/providers/providers.models.ts
  ui/src/app/shared/components/business-components/card/card.component.html
  ui/src/app/shared/components/business-components/card/card.component.scss
  ui/src/app/shared/components/business-components/card/card.component.ts
  ui/src/app/shared/components/business-components/provider-card/provider-card.component.html
  ui/src/app/shared/components/business-components/provider-card/provider-card.component.scss
  ui/src/app/shared/components/business-components/provider-card/provider-card.component.ts
  ui/src/app/shared/components/dynamic-components/providers/habitica/habitica.component.ts
  ui/src/app/shared/components/popup/popup.component.ts
  ui/src/app/shared/components/popup/popup.model.ts
  ui/src/app/shared/helpers/error.interceptor.ts
  ui/src/app/store/actions/menu.actions.ts
  ui/src/app/store/reducers/app.reducers.ts
  ui/src/app/store/selectors/menu.selectors.ts
  ui/src/assets/styles/common.scss
  ui/src/assets/styles/variables.scss
  ui/src/styles.scss
Labels: enhancement

#82 habitica put
  ui/src/app/pages/admin/providers/providers.component.ts
  ui/src/app/pages/admin/providers/providers.service.ts
  ui/src/app/shared/components/business-components/provider-card/provider-card.component.html
  ui/src/app/shared/components/business-components/provider-card/provider-card.component.ts
  ui/src/app/shared/components/dynamic-components/providers/habitica/habitica.component.html
  ui/src/app/shared/components/dynamic-components/providers/habitica/habitica.component.ts
  ui/src/app/shared/components/popup/popup.component.ts
  ui/src/app/shared/services/api.service.ts
  ui/src/app/shared/utils.ts
Labels: enhancement

#87 refresh token, signout, style fixes
  ui/src/app/pages/admin/admin.component.html
  ui/src/app/pages/admin/admin.component.scss
  ui/src/app/pages/admin/dashboard/dashboard.component.scss
  ui/src/app/pages/admin/providers/providers.component.scss
  ui/src/app/pages/authentication/authentication.service.ts
  ui/src/app/shared/components/business-components/provider-card/provider-card.component.scss
  ui/src/app/shared/components/header/header.component.scss
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/constants.ts
  ui/src/app/shared/helpers/error.interceptor.ts
  ui/src/app/shared/services/api.service.ts
  ui/src/assets/styles/mixins/admin-theme.component.scss
Labels: enhancement

#88 refactoring, refresh token
  ui/src/app/pages/authentication/authentication.module.ts
  ui/src/app/pages/authentication/authentication.service.ts
  ui/src/app/pages/authentication/signin/signin.component.html
  ui/src/app/pages/authentication/signup/signup.component.html
  ui/src/app/pages/authentication/user.model.ts
  ui/src/app/shared/components/auth-form/auth-form.component.html
  ui/src/app/shared/components/auth-form/auth-form.component.scss
  ui/src/app/shared/components/auth-form/auth-form.component.ts
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/helpers/error.interceptor.ts
  ui/src/app/shared/helpers/jwt.interceptors.ts
  ui/src/app/shared/helpers/token.interceptor.ts
  ui/src/app/shared/services/notification.service.ts
  ui/src/assets/styles/mixins/auth-form-theme.component.scss
  ui/src/styles.scss
Labels: enhancement

#94 Feature/update api models
  ui/apis/habitica/ApiModels.yml
  ui/apis/tasks/ApiModels.yml
Labels: enhancement

#95 refactoring part 1
  ui/src/app/pages/admin/providers/providers.component.html
  ui/src/app/pages/admin/providers/providers.component.ts
  ui/src/app/pages/admin/providers/providers.service.ts
  ui/src/app/pages/authentication/authentication.module.ts
  ui/src/app/pages/authentication/authentication.service.ts
  ui/src/app/pages/authentication/user.model.ts
  ui/src/app/shared/components/auth-form/auth-form.component.ts
  ui/src/app/shared/components/business-components/provider-card/provider-card.component.ts
  ui/src/app/shared/components/dynamic-components/providers/habitica/habitica.component.ts
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/guards/auth.guard.ts
  ui/src/app/shared/helpers/error.interceptor.ts
  ui/src/app/shared/helpers/jwt.interceptors.ts
  ui/src/app/shared/helpers/token.interceptor.ts
  ui/src/app/shared/services/api.service.ts
  ui/src/assets/styles/mixins/header-theme.component.scss
Labels: enhancement

#96 refactoring part 2
  ui/src/app/app.module.ts
  ui/src/app/pages/admin/admin.module.ts
  ui/src/app/pages/admin/providers/providers.component.ts
  ui/src/app/pages/admin/providers/providers.service.ts
  ui/src/app/shared/components/auth-form/auth-form.component.html
  ui/src/app/shared/components/auth-form/auth-form.component.ts
  ui/src/app/shared/components/business-components/provider-card/provider-card.component.ts
  ui/src/app/shared/components/notifications/notification.service.ts
  ui/src/app/shared/components/notifications/simple/simple-notification.component.html
  ui/src/app/shared/components/notifications/simple/simple-notification.component.scss
  ui/src/app/shared/components/notifications/simple/simple-notification.component.ts
  ui/src/app/shared/components/popup/popup.model.ts
  ui/src/app/shared/constants.ts
  ui/src/app/shared/services/notification.service.ts
  ui/src/app/shared/shared.module.ts
Labels: enhancement

#98 refactoring part 3
  ui/src/app/app.component.html
  ui/src/app/app.component.scss
  ui/src/app/app.component.ts
  ui/src/app/app.module.ts
  ui/src/app/pages/admin/providers/providers.component.ts
  ui/src/app/shared/components/auth-form/auth-form.component.ts
  ui/src/app/shared/components/notifications/notification.service.ts
  ui/src/app/shared/services/api.service.ts
  ui/src/assets/styles/common.scss
Labels: enhancement

#99 common loading indicator, main states
  ui/src/app/app.component.html
  ui/src/app/app.component.scss
  ui/src/app/app.component.ts
  ui/src/app/pages/admin/providers/providers.component.ts
  ui/src/app/shared/components/auth-form/auth-form.component.html
  ui/src/app/shared/components/auth-form/auth-form.component.ts
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/store/actions/main.actions.ts
  ui/src/app/store/reducers/app.reducers.ts
  ui/src/app/store/reducers/main.reducers.ts
  ui/src/app/store/selectors/main.selectors.ts
  ui/src/app/store/state/app.state.ts
  ui/src/app/store/state/main.state.ts
  ui/src/assets/styles/common.scss
Labels: enhancement

#100 Feature/menu
  ui/src/app/app.component.ts
  ui/src/app/pages/admin/admin.component.html
  ui/src/app/pages/admin/admin.component.scss
  ui/src/app/pages/admin/admin.component.ts
  ui/src/app/pages/admin/admin.module.ts
  ui/src/app/pages/admin/providers/providers.component.ts
  ui/src/app/shared/common.models.ts
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/components/menu/left-menu/left-menu.component.html
  ui/src/app/shared/components/menu/left-menu/left-menu.component.scss
  ui/src/app/shared/components/menu/left-menu/left-menu.component.ts
  ui/src/app/shared/components/menu/menu.animations.ts
  ui/src/app/shared/components/menu/menu.component.html
  ui/src/app/shared/components/menu/menu.component.scss
  ui/src/app/shared/components/menu/menu.component.ts
  ui/src/app/shared/components/menu/menu.model.ts
  ui/src/app/shared/components/menu/right-menu/right-menu.component.html
  ui/src/app/shared/components/menu/right-menu/right-menu.component.scss
  ui/src/app/shared/components/menu/right-menu/right-menu.component.ts
  ui/src/app/shared/shared.module.ts
  ui/src/app/store/actions/menu.actions.ts
  ui/src/app/store/reducers/menu.reducers.ts
  ui/src/app/store/selectors/menu.selectors.ts
  ui/src/app/store/state/menu.state.ts
Labels: enhancement

#101 stylings
  ui/src/app/app.component.ts
  ui/src/app/pages/admin/admin.component.html
  ui/src/app/pages/admin/admin.component.scss
  ui/src/app/pages/admin/admin.component.ts
  ui/src/app/pages/admin/dashboard/dashboard.component.html
  ui/src/app/pages/admin/dashboard/dashboard.component.scss
  ui/src/app/shared/components/header/header.component.scss
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/components/menu/left-menu/left-menu.component.html
  ui/src/app/shared/components/menu/left-menu/left-menu.component.scss
  ui/src/app/shared/components/menu/menu.animations.ts
  ui/src/app/shared/components/menu/right-menu/right-menu.component.html
  ui/src/app/shared/components/menu/right-menu/right-menu.component.scss
  ui/src/app/shared/components/menu/right-menu/right-menu.component.ts
  ui/src/app/shared/shared.module.ts
  ui/src/app/store/reducers/menu.reducers.ts
  ui/src/assets/styles/common.scss
  ui/src/assets/styles/mixins/menu-theme.component.scss
  ui/src/assets/styles/mixins/right-menu-theme.component.scss
  ui/src/assets/styles/variables.scss
  ui/src/styles.scss
Labels: enhancement

#103 fix matrix
  ui/src/app/pages/admin/dashboard/dashboard.component.scss
Labels: bug

#104 left menu in dashboard
  ui/src/app/pages/admin/admin.component.html
  ui/src/app/pages/admin/dashboard/dashboard.component.html
  ui/src/app/pages/admin/dashboard/dashboard.component.scss
  ui/src/app/pages/admin/dashboard/dashboard.component.ts
  ui/src/app/shared/components/header/header.component.html
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/components/menu/menu.animations.ts
  ui/src/app/shared/helpers/token.interceptor.ts
  ui/src/assets/styles/common.scss
Labels: enhancement

#105 refactoring & ngrx effects init
  ui/src/app/pages/admin/dashboard/dashboard.component.html
  ui/src/app/pages/admin/dashboard/dashboard.component.scss
  ui/src/app/pages/admin/providers/providers.component.ts
  ui/src/app/shared/components/auth-form/auth-form.component.ts
  ui/src/app/shared/components/header/header.component.html
  ui/src/app/shared/components/header/header.component.scss
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/components/menu/left-menu/left-menu.component.ts
  ui/src/app/shared/components/menu/menu.animations.ts
  ui/src/app/shared/components/menu/right-menu/right-menu.component.ts
  ui/src/app/store/actions/providers.actions.ts
  ui/src/app/store/effects/providers.effects.ts
  ui/src/app/store/reducers/app.reducers.ts
  ui/src/app/store/reducers/providers.reducers.ts
  ui/src/app/store/selectors/providers.selectors.ts
  ui/src/app/store/state/app.state.ts
  ui/src/app/store/state/providers.state.ts
Labels: enhancement

#106 ngrx effects init, bug fix
  ui/src/app/app.module.ts
  ui/src/app/pages/admin/providers/providers.component.ts
  ui/src/app/pages/admin/providers/providers.service.ts
  ui/src/app/shared/components/dynamic-components/providers/google/google.component.ts
  ui/src/app/shared/components/dynamic-components/providers/microsoft/microsoft.component.ts
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/components/popup/popup.component.ts
  ui/src/app/store/effects/providers.effects.ts
  ui/src/app/store/reducers/app.reducers.ts
  ui/src/app/store/reducers/providers.reducers.ts
  ui/src/app/store/selectors/providers.selectors.ts
  ui/src/app/store/state/app.state.ts
  ui/tsconfig.json
Labels: bug

#108 version 1.0.3
  ui/package.json
Labels: documentation

#110 providers.service
  ui/src/app/pages/admin/providers/providers.service.ts
Labels: bug

#111 Master
  ui/src/app/pages/admin/providers/providers.service.ts
Labels: bug

#112 fix menu
  ui/src/app/shared/components/menu/left-menu/left-menu.component.ts
  ui/src/app/shared/components/menu/right-menu/right-menu.component.ts
Labels: bug

#113 fix menu
  ui/src/app/shared/components/menu/left-menu/left-menu.component.ts
  ui/src/app/shared/components/menu/right-menu/right-menu.component.ts
Labels: bug

#116 drag&drop between matrix
  ui/angular.json
  ui/package-lock.json
  ui/package.json
  ui/src/app/pages/admin/admin.module.ts
  ui/src/app/pages/admin/dashboard/dashboard.component.html
  ui/src/app/pages/admin/dashboard/dashboard.component.scss
  ui/src/app/pages/admin/dashboard/dashboard.component.ts
  ui/src/app/pages/admin/dashboard/dashboard.service.ts
  ui/src/app/shared/components/business-components/task-card/task-card.component.html
  ui/src/app/shared/components/business-components/task-card/task-card.component.scss
  ui/src/app/shared/components/header/header.component.html
  ui/src/app/shared/components/menu/left-menu/left-menu.component.html
  ui/src/app/shared/components/menu/left-menu/left-menu.component.scss
  ui/src/app/shared/constants.ts
  ui/src/assets/fake-data/tasks.json
Labels: enhancement

#117 fix build issue
  ui/src/app/pages/admin/dashboard/dashboard.component.scss
  ui/src/app/pages/admin/dashboard/dashboard.component.ts
  ui/src/app/shared/components/business-components/task-card/task-card.component.ts
  ui/src/app/shared/constants.ts
Labels: bug
