Repository lionize/WebUI, pull requests merged in 2019-08, with the labels that each got.

#15 migrated to angular 8.2.0
  README.md
  ui/.editorconfig
  ui/.gitignore
  ui/angular.json
  ui/browserslist
  ui/e2e/protractor.conf.js
  ui/e2e/src/app.e2e-spec.ts
  ui/e2e/src/app.po.ts
  ui/e2e/tsconfig.json
  ui/karma.conf.js
  ui/nginx.conf
  ui/package-lock.json
  ui/package.json
  ui/public/favicon.ico
  ui/public/index.html
  ui/public/manifest.json
  ui/src/App.js
  ui/src/App.scss
  ui/src/App.test.js
  ui/src/app/app.component.html
  ui/src/app/app.component.scss
  ui/src/app/app.component.spec.ts
  ui/src/app/app.component.ts
  ui/src/app/app.module.ts
  ui/src/app/app.routing.module.ts
  ui/src/assets/.gitkeep
  ui/src/assets/fonts/Roboto-Bold.ttf
  ui/src/assets/fonts/Roboto-Light.ttf
  ui/src/assets/fonts/Roboto-Regular.ttf
  ui/src/assets/styles/variables.scss
  ui/src/components/bussiness-components/LionizeCard.js
  ui/src/components/footer/Footer.js
  ui/src/components/footer/Footer.scss
  ui/src/components/header/Header.js
  ui/src/components/header/Header.scss
  ui/src/containers/main/Main.js
  ui/src/containers/main/Main.scss
  ui/src/environments/environment.prod.ts
  ui/src/environments/environment.ts
  ui/src/favicon.ico
  ui/src/index.html
  ui/src/index.js
  ui/src/index.scss
  ui/src/main.ts
  ui/src/polyfills.ts
  ui/src/serviceWorker.js
  ui/src/styles.scss
  ui/src/test.ts
  ui/tsconfig.app.json
  ui/tsconfig.json
  ui/tsconfig.spec.json
  ui/tslint.json
Labels: enhancement

#16 styles, fonts, theme, layout, main routing, main components, etc.
  ui/package-lock.json
  ui/package.json
  ui/src/app/app-theme.component.scss
  ui/src/app/app.component.html
  ui/src/app/app.module.ts
  ui/src/app/app.routing.module.ts
  ui/src/app/pages/private/admin/admin.component.html
  ui/src/app/pages/private/admin/admin.component.scss
  ui/src/app/pages/private/admin/admin.component.ts
  ui/src/app/pages/private/admin/admin.module.ts
  ui/src/app/pages/private/admin/admin.routing.module.ts
  ui/src/app/pages/private/admin/dashboard/dashboard.component.html
  ui/src/app/pages/private/admin/dashboard/dashboard.component.scss
  ui/src/app/pages/private/admin/dashboard/dashboard.component.ts
  ui/src/app/pages/private/header/header.component.html
  ui/src/app/pages/private/header/header.component.scss
  ui/src/app/pages/private/header/header.component.ts
  ui/src/app/pages/public/landing/landing.component.html
  ui/src/app/pages/public/landing/landing.component.scss
  ui/src/app/pages/public/landing/landing.component.ts
  ui/src/app/pages/public/login/login.component.html
  ui/src/app/pages/public/login/login.component.scss
  ui/src/app/pages/public/login/login.component.ts
  ui/src/app/shared/components/dialog/dialog.component.html
  ui/src/app/shared/components/dialog/dialog.component.scss
  ui/src/app/shared/components/dialog/dialog.component.ts
  ui/src/app/shared/components/footer/footer.component.html
  ui/src/app/shared/components/footer/footer.component.scss
  ui/src/app/shared/components/footer/footer.component.ts
  ui/src/app/shared/constants.ts
  ui/src/app/shared/guards/auth.guard.ts
  ui/src/app/shared/helpers/jwt.interceptors.ts
  ui/src/app/shared/helpers/validators.ts
  ui/src/app/shared/services/api.service.ts
  ui/src/app/shared/services/sharing.service.ts
  ui/src/app/shared/utils.ts
  ui/src/assets/fonts/Material.woff2
  ui/src/assets/fonts/Roboto-Bold.ttf
  ui/src/assets/fonts/Roboto-Light.ttf
  ui/src/assets/fonts/Roboto-Regular.ttf
  ui/src/assets/styles/fonts.scss
  ui/src/assets/styles/mixins.scss
  ui/src/assets/styles/themes/eisenhower-theme.scss
  ui/src/assets/styles/variables.scss
  ui/src/styles.scss
Labels: enhancement

#17 main routes, components
  ui/src/app/app.component.html
  ui/src/app/app.component.scss
  ui/src/app/app.module.ts
  ui/src/app/app.routing.module.ts
  ui/src/app/pages/private/admin/admin.component.scss
  ui/src/app/pages/private/admin/admin.component.ts
  ui/src/app/pages/private/admin/admin.module.ts
  ui/src/app/pages/private/admin/dashboard/dashboard.component.html
  ui/src/app/pages/private/admin/dashboard/dashboard.component.ts
  ui/src/app/pages/private/header/header.component.scss
  ui/src/app/pages/private/header/header.component.ts
  ui/src/app/pages/public/landing/landing.component.html
  ui/src/app/pages/public/landing/landing.component.scss
  ui/src/app/pages/public/landing/landing.component.ts
  ui/src/app/pages/public/login/login.component.scss
  ui/src/app/pages/public/login/login.component.ts
  ui/src/app/shared/components/dialog/dialog.component.ts
  ui/src/app/shared/components/footer/footer.component.html
  ui/src/app/shared/components/footer/footer.component.ts
  ui/src/app/shared/guards/auth.guard.ts
  ui/src/styles.scss
Labels: enhancement

#18 feature: fake login
  ui/angular.json
  ui/package-lock.json
  ui/package.json
  ui/src/app/app.module.ts
  ui/src/app/app.routing.module.ts
  ui/src/app/pages/private/admin/admin.component.scss
  ui/src/app/pages/private/admin/dashboard/dashboard.component.html
  ui/src/app/pages/private/header/header.component.html
  ui/src/app/pages/private/header/header.component.scss
  ui/src/app/pages/private/header/header.component.ts
  ui/src/app/pages/public/landing/landing.component.html
  ui/src/app/pages/public/login/login.component.html
  ui/src/app/pages/public/login/login.component.scss
  ui/src/app/pages/public/login/login.component.ts
  ui/src/app/pages/public/public.module.ts
  ui/src/app/pages/public/public.routing.module.ts
  ui/src/app/shared/components/footer/footer.component.html
  ui/src/app/shared/guards/auth.guard.ts
  ui/src/assets/fonts/Material.woff2
  ui/src/assets/styles/fonts.scss
  ui/src/assets/styles/variables.scss
  ui/src/styles.scss
Labels: enhancement

#19 Update psakefile.ps1
  psakefile.ps1
Labels: bug

#20 refactoring, validations added
  psakefile.ps1
  ui/src/app/app.module.ts
  ui/src/app/app.routing.module.ts
  ui/src/app/pages/public/footer/footer.component.html
  ui/src/app/pages/public/footer/footer.component.scss
  ui/src/app/pages/public/footer/footer.component.ts
  ui/src/app/pages/public/login/login.component.html
  ui/src/app/pages/public/login/login.component.ts
  ui/src/app/pages/public/public.module.ts
  ui/src/app/shared/constants.ts
  ui/src/app/shared/models/shared.models.ts
  ui/src/app/shared/utils.ts
  ui/src/app/shared/validation.messages.ts
Labels: enhancement

#22 Bugfix/build fix
  .gitignore
  psakefile.ps1
  ui/nginx.conf
Labels: bug

#21 refactoring
  ui/src/app/app-theme.component.scss
  ui/src/app/app.component.ts
  ui/src/app/pages/private/admin/admin.module.ts
  ui/src/app/pages/public/login/login.component.html
  ui/src/app/pages/public/login/login.component.ts
  ui/src/app/pages/public/login/user.model.ts
  ui/src/app/pages/public/public.module.ts
  ui/src/app/shared/components/dialog/dialog.component.ts
  ui/src/app/shared/components/footer/footer.component.html
  ui/src/app/shared/components/footer/footer.component.scss
  ui/src/app/shared/components/footer/footer.component.ts
  ui/src/app/shared/components/header/header.component.html
  ui/src/app/shared/components/header/header.component.scss
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/helpers/form.validators.ts
  ui/src/app/shared/helpers/jwt.interceptors.ts
  ui/src/app/shared/helpers/validators.ts
  ui/src/app/shared/services/api.service.ts
  ui/src/app/shared/services/message.service.ts
  ui/src/app/shared/services/sharing.service.ts
  ui/src/app/shared/utils.ts
  ui/src/assets/images/lionize_logo.jpg
  ui/src/index.html
  ui/src/styles.scss
Labels: enhancement

#23 styling
  ui/src/app/pages/private/admin/admin.component.scss
  ui/src/app/pages/private/admin/admin.module.ts
  ui/src/app/pages/private/admin/dashboard/dashboard.component.scss
  ui/src/app/shared/components/dialog/dialog.component.scss
  ui/src/app/shared/components/header/header.component.html
  ui/src/app/shared/components/header/header.component.scss
  ui/src/app/shared/shared.module.ts
  ui/src/assets/images/lionize_logo_large.jpg
  ui/src/assets/styles/common.scss
  ui/src/assets/styles/mixins.scss
  ui/src/assets/styles/variables.scss
Labels: enhancement

#24 environments added
  ui/angular.json
  ui/package.json
  ui/src/app/shared/components/header/header.component.ts
  ui/src/environments/environment.prod.ts
  ui/src/environments/environment.ts
Labels: enhancement

#27 environments, signin
  ui/angular.json
  ui/package.json
  ui/src/app/pages/public/authentication/authentication.service.ts
  ui/src/app/pages/public/authentication/login/login.component.ts
  ui/src/app/pages/public/authentication/register/register.component.ts
  ui/src/app/shared/components/header/header.component.html
  ui/src/app/shared/constants.ts
  ui/src/environments/environment.prod.ts
  ui/src/environments/environment.ts
  ui/src/environments/environments.loc.ts
Labels: enhancement

#28 enum API_URLS
  ui/src/app/shared/constants.ts
Labels: bug

#29 some styling
  ui/src/app/pages/private/admin/admin.component.scss
  ui/src/app/pages/private/admin/dashboard/dashboard.component.scss
  ui/src/app/shared/components/header/header.component.scss
  ui/src/assets/styles/common.scss
Labels: enhancement

#30 default build added
  ui/package.json
Labels: bug

#31 Update psakefile.ps1
  psakefile.ps1
Labels: bug

#32 test cards added
  ui/src/app/pages/private/admin/admin.module.ts
  ui/src/app/pages/private/admin/dashboard/dashboard.component.html
  ui/src/app/pages/private/admin/dashboard/dashboard.component.scss
  ui/src/app/pages/private/admin/dashboard/dashboard.component.ts
  ui/src/app/shared/components/business-components/li-card/li-card.component.html
  ui/src/app/shared/components/business-components/li-card/li-card.component.scss
  ui/src/app/shared/components/business-components/li-card/li-card.component.ts
  ui/src/assets/styles/themes/eisenhower-theme.scss
  ui/src/assets/styles/variables.scss
  ui/src/styles.scss
Labels: enhancement

#33 package.json version added
  ui/package.json
Labels: documentation

#35 test
  ui/src/app/shared/components/business-components/li-card/li-card.component.html
Labels: enhancement

#41 Feature/publish version
  Publish.ps1
  psakefile.ps1
Labels: enhancement

#45 styling
  ui/src/app/shared/components/dialog/dialog.component.html
  ui/src/app/shared/components/header/header.component.ts
  ui/src/assets/styles/themes/eisenhower-theme.scss
Labels: enhancement

#47 Signin, Signup, refactoring
  ui/angular.json
  ui/package.json
  ui/src/app/app.module.ts
  ui/src/app/pages/public/authentication/authentication.service.ts
  ui/src/app/pages/public/authentication/login/login.component.html
  ui/src/app/pages/public/authentication/login/login.component.ts
  ui/src/app/pages/public/authentication/register/register.component.html
  ui/src/app/pages/public/authentication/register/register.component.ts
  ui/src/app/pages/public/authentication/user.model.ts
  ui/src/app/pages/public/public.routing.module.ts
  ui/src/app/shared/models/shared.models.ts
  ui/src/app/shared/services/api.service.ts
  ui/src/assets/styles/fonts.scss
  ui/src/environments/environment.prod.ts
  ui/src/environments/environment.ts
  ui/src/environments/environments.loc.ts
Labels: enhancement

#48 fix: minor
  ui/src/app/shared/services/api.service.ts
Labels: enhancement

#49 authentication bug fix
  ui/src/app/pages/public/authentication/login/login.component.ts
  ui/src/app/shared/guards/auth.guard.ts
  ui/src/app/shared/services/api.service.ts
Labels: bug

#50 authentication enhancement
  ui/src/app/pages/private/admin/dashboard/dashboard.component.html
  ui/src/app/pages/public/authentication/login/login.component.html
  ui/src/app/pages/public/authentication/login/login.component.ts
  ui/src/app/pages/public/authentication/register/register.component.html
  ui/src/app/pages/public/landing/landing.component.html
  ui/src/app/shared/services/api.service.ts
Labels: enhancement

#51 authentication enhancement
  ui/src/app/pages/public/authentication/authentication.service.ts
  ui/src/app/pages/public/authentication/login/login.component.ts
  ui/src/app/pages/public/authentication/register/register.component.ts
  ui/src/app/pages/public/authentication/user.model.ts
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/constants.ts
  ui/src/app/shared/services/api.service.ts
Labels: enhancement

#52 stash testing
  ui/src/app/pages/public/authentication/authentication.service.ts
  ui/src/app/shared/constants.ts
Labels: enhancement

#54 api.service.ts, menu init
  ui/src/app/pages/private/admin/admin.component.html
  ui/src/app/pages/private/admin/admin.module.ts
  ui/src/app/pages/public/authentication/authentication.service.ts
  ui/src/app/shared/components/header/header.component.html
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/components/menu/menu.component.html
  ui/src/app/shared/components/menu/menu.component.scss
  ui/src/app/shared/components/menu/menu.component.ts
  ui/src/app/shared/services/api.service.ts
Labels: enhancement

#56 ngrx init, menu init
  ui/package-lock.json
  ui/package.json
  ui/src/app/app.module.ts
  ui/src/app/pages/private/admin/admin.component.html
  ui/src/app/pages/private/admin/admin.component.scss
  ui/src/app/pages/private/admin/admin.component.ts
  ui/src/app/pages/private/admin/admin.module.ts
  ui/src/app/pages/private/admin/dashboard/dashboard.component.html
  ui/src/app/pages/private/admin/dashboard/dashboard.component.scss
  ui/src/app/pages/public/authentication/login/login.component.html
  ui/src/app/pages/public/authentication/register/register.component.html
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/components/menu/menu.component.html
  ui/src/app/shared/components/menu/menu.component.scss
  ui/src/app/shared/components/menu/menu.component.ts
  ui/src/app/shared/components/menu/menu.model.ts
  ui/src/app/store/actions/menu.actions.ts
  ui/src/app/store/reducers/app.reducers.ts
  ui/src/app/store/reducers/menu.reducers.ts
  ui/src/app/store/selectors/menu.selectors.ts
  ui/src/app/store/state/app.state.ts
  ui/src/app/store/state/menu.state.ts
  ui/src/assets/styles/variables.scss
  ui/src/styles.scss
Labels: enhancement

#58 fix: build issue
  ui/src/app/store/reducers/menu.reducers.ts
Labels: bug

#59 styles
  ui/src/app/app.component.scss
  ui/src/app/pages/private/admin/admin.component.scss
  ui/src/app/pages/private/admin/admin.component.ts
  ui/src/app/pages/public/authentication/login/login.component.scss
  ui/src/app/pages/public/authentication/register/register.component.scss
  ui/src/app/pages/public/landing/landing.component.scss
  ui/src/app/shared/components/dialog/dialog.component.scss
  ui/src/app/shared/components/header/header.component.html
  ui/src/app/shared/components/header/header.component.scss
  ui/src/app/shared/components/menu/menu.component.html
  ui/src/app/shared/components/menu/menu.component.scss
  ui/src/app/shared/components/menu/menu.component.ts
  ui/src/assets/styles/common.scss
  ui/src/styles.scss
Labels: enhancement

#62 fix: build issue
  ui/src/app/app.module.ts
  ui/src/app/app.routing.module.ts
  ui/src/app/shared/components/business-components/li-card/li-card.component.html
  ui/src/app/shared/components/business-components/li-card/li-card.component.ts
Labels: bug

#63 fix: routing
  ui/src/app/app.routing.module.ts
  ui/src/app/pages/admin/admin.routing.module.ts
  ui/src/app/pages/authentication/authentication.module.ts
  ui/src/app/pages/authentication/authentication.routing.module.ts
  ui/src/app/pages/authentication/authentication.service.ts
  ui/src/app/pages/landing/landing.component.html
  ui/src/app/pages/landing/landing.routing.module.ts
  ui/src/app/shared/components/header/header.component.ts
  ui/src/app/shared/components/li-auth/li-auth.component.ts
  ui/src/app/shared/guards/auth.guard.ts
  ui/src/app/shared/services/api.service.ts
Labels: bug
